[package]
name = "jpgfuzz"
version = "0.1.0"
authors = ["ls4508 <ls4508@nyu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
debugger = { path = "libs/debugger" }
